server:
  port: 8081
spring:
  application:
    name: auth-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    database: postgresql
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}