include:
  - gateway/compose.yaml
  - auth-service/compose.yaml
  - webapi/compose.yaml
  - user-service/compose.yaml
  - email-service/compose.yaml
  - payment-service/compose.yaml

networks:
  hkd-network:
    driver: bridge
    name: hkd-network