server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service-route
          uri: http://auth-service:8081
          predicates:
            - Path=/auth/**
        - id: app-demo-route
          uri: http://webapi:8083
          predicates:
            - Path=/api/**
        - id: product-service-route
          uri: http://product-service:8082
          predicates:
            - Path=/products/**
#          filters:
#            - AuthFilter
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway