server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service-route
          uri: http://auth-service:8081
          predicates:
            - Path=/api/auth/**
        - id: app-demo-route
          uri: http://webapi:8083
          predicates:
            - Path=/api/hkd/**
        - id: product-service-route
          uri: http://product-service:8082
          predicates:
            - Path=/products/**
          filters:
            - AuthFilter
        - id: user-service-route
          uri: http://user-service:8084
          predicates:
            - Path=/api/users/**
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway
logging:
  level:
    org.springframework.web.HttpLogging: TRACE
    reactor.netty.http.server: DEBUG
    reactor.netty.http.client: DEBUG
