services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: makiseemi/hkd-auth-service
    container_name: auth-service
    environment:
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - SECRET_KEY=${SECRET_KEY}
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=*:${DEBUG_PORT},server=y,suspend=n
    ports:
      - "8081:8081"
      - "${DEBUG_PORT}:${DEBUG_PORT}"
    networks:
      - hkd-auth-service-network

  userdb:
    image: postgres:14
    container_name: userdb
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - "5433:5432"
    networks:
      - hkd-auth-service-network

networks:
  hkd-auth-service-network:
    name: hkd-network
    external: true