services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: makiseemi/hkd-auth-service
    container_name: auth-service
    environment:
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${USER_DB_HOST}
      - SECRET_KEY=${SECRET_KEY}
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=*:${AUTH_DEBUG_PORT},server=y,suspend=n
    ports:
      - "${AUTH_PUBLISH_PORT}:8081"
      - "${AUTH_DEBUG_PORT}:${AUTH_DEBUG_PORT}"
    networks:
      - hkd-auth-service-network
    depends_on:
      - user-service
      - userdb

networks:
  hkd-auth-service-network:
    name: hkd-network
    external: true