services:
  payment-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: makiseemi/hkd-payment-service
    container_name: payment-service
    environment:
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - SECRET_KEY=${SECRET_KEY}
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=*:${PAYMENT_DEBUG_PORT},server=y,suspend=n
      - VNPAY_TMNCODE=${VNPAY_TMNCODE}
      - VNPAY_HASH_SECRET=${VNPAY_HASH_SECRET}
    ports:
      - "${PAYMENT_PUBLISH_PORT}:8086"
      - "${PAYMENT_DEBUG_PORT}:${PAYMENT_DEBUG_PORT}"
    networks:
      - hkd-payment-network
    depends_on:
      - payment-db

  payment-db:
    image: postgres:14
    container_name: payment-db
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=Asia/HoChiMinh
    ports:
      - "${PAYMENT_PUBLISH_DB_PORT}:5432"
    networks:
      - hkd-payment-network

networks:
  hkd-payment-network:
    name: hkd-network
    external: true