server:
  port: 8083
spring:
  application:
    name: webapi
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5433/hkd-db
    username: admin
    password: andy9999
  flyway:
    baseline-on-migrate: true
logging:
  level:
    org:
      flywaydb: debug

