server:
  port: 8083
spring:
  application:
    name: webapi
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  flyway:
    baseline-on-migrate: true
logging:
  level:
    org:
      flywaydb: debug

